<?php
require_once 'PHPUnit/Framework.php';

require_once 'bootstrap.php';

/**
 * Test class for RSS.
 * Generated by PHPUnit on 2011-02-01 at 21:15:17.
 */
class RSSTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var RSS
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new RSS;
        $this->xml = file_get_contents(PATH_TEST_DATA . '/rss.xml');
        $this->response = $this->object->getParsedResponse($this->xml);
    }

    /**
     * testGetParsedResponse().
     */
    public function testGetParsedResponse()
    {
        $this->assertType('array', $this->response);
    }

    /**
     * testGetParsedResponseHasItems().
     */
    public function testGetParsedResponseHasItems()
    {
        $this->assertArrayHasKey('items', $this->response);
    }
}