<?php // this is an autogenerated file - do not edit (created Wed, 02 Feb 2011 00:32:35 +0100)
function autoload4d48981322536($class) {
  static $classes = null;
  if ($classes === null) {
    $classes = array(
            'fscache' => '/WCC.php',
            'http' => '/WCC.php',
            'rss' => '/RSS.php',
            'sparql' => '/SPARQL.php',
            'urlcache' => '/WCC.php',
            'wcc' => '/WCC.php',
            'youtube' => '/YouTube.php'
            );
  }
  $cn = strtolower($class);
  if (isset($classes[$cn])) {
    require dirname(__FILE__) . $classes[$cn];
  }
}
spl_autoload_register('autoload4d48981322536');