<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload4f022a66c0d4e($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'dbpediaresource' => '/DBpediaResource.php',
            'fscache' => '/WCC.php',
            'http' => '/WCC.php',
            'rss' => '/RSS.php',
            'sparql' => '/SPARQL.php',
            'urlcache' => '/WCC.php',
            'wcc' => '/WCC.php',
            'youtube' => '/YouTube.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload4f022a66c0d4e');
// @codeCoverageIgnoreEnd